# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-16 07:42
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dashboard', '0002_auto_20161206_1639'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='firstName',
        ),
        migrations.RemoveField(
            model_name='account',
            name='lastName',
        ),
        migrations.RemoveField(
            model_name='account',
            name='middleName',
        ),
        migrations.AddField(
            model_name='account',
            name='user',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
