# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-16 10:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_auto_20161216_1442'),
    ]

    operations = [
        migrations.RenameField(
            model_name='history',
            old_name='user',
            new_name='account',
        ),
    ]
