# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-16 12:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_auto_20161216_1833'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
