# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-16 12:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_auto_20161216_1913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
