# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-24 10:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_meal_imgurl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meal',
            name='imgurl',
            field=models.CharField(max_length=1024),
        ),
    ]
